### ISSUE TITLE
unhandled pull requests

### ISSUE THREAD

**Issue by glensc** [edderrd/skype-logs#8]
have you considered adding me as Collabrator, so could merge in things more easily?

currently there are 4 unhandled pull requests

asked it already 20 days ago in fact:
https://github.com/edderrd/skype-logs/pull/5#issuecomment-192287264

**Comment by glensc** [comment]
@edderrd please merge my PR's. i no longer need the tool (as the conversion is done), so i won't be able to support any of those.

- #4
- #5
- #6
- #7

**Comment by edderrd** [comment]
@glensc now you're a collaborator 👍

**Comment by glensc** [comment]
PR list is empty. This can be closed.
